# Generated by Django 5.0.7 on 2024-08-02 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usuario_cpf_alter_contabancariausuario_numero_conta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
