# Generated by Django 5.0.6 on 2024-08-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancariausuario',
            name='versao',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
