# Generated by Django 5.0.7 on 2024-08-02 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_remove_usuario_cpf_alter_usuario_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_apos_transacao', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_transacao', models.PositiveSmallIntegerField(choices=[('DEP', 'Depósito'), ('SAQ', 'Saque'), ('TRA', 'Transferência')])),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='accounts.contabancariausuario')),
                ('conta_recebedora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_recebidas', to='accounts.contabancariausuario')),
            ],
            options={
                'ordering': ['data_hora'],
            },
        ),
    ]
