# Generated by Django 5.0.7 on 2024-08-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='tipo_transacao',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Depósito'), (2, 'Saque'), (4, 'Transferência')]),
        ),
    ]
